### PR TITLE
EKF: Allow fallback to non-aiding mode if external vision fusion is lost

### PR DESCRIPTION
**Pull request by priseborough**
Addresses https://github.com/PX4/Firmware/issues/7491#issuecomment-312613868

### CODE REVIEW

**Comment by TobiMiller** [comment]
Ok @priseborough . I have tested it. Now vision fusion is completely broken for x and y.
http://logs.px4.io/plot_app?log=5473b79d-b15b-4acb-b11f-d7278f8ec406

i have checked out PX4 firmware master branch and updated the ecl submodule to master and pulled the request. ==> PX4 firmware got some build errors

so i put your lines manually in the control.cpp and compiled it successfully. thats the result.

**Comment by priseborough** [comment]
OK, I will run your log through replay today and see what is going on

**Comment by priseborough** [comment]
@TobiMiller I don't know what happened with that build, but the EKF2 parameters are missing from the file. These patches should build cleanly on master now, so can you please do a 'make distclean' after you pull them in before building, generate another log.

TXS

**Comment by TobiMiller** [comment]
http://logs.px4.io/plot_app?log=620933e1-e636-40e5-a52b-3af840f0303e

Looks the same. I cloned the px4 master clean. went to the ecl dir. fetched the PR in a new local branch and checked it out. on compilation it asked if i am an expert and i pressed "y".

i have reset all params and calibrated everything.

**Comment by LorenzMeier** [comment]
Can you test on master again with this ECL patch?

there was a recent fix that you most likely needed:
https://github.com/PX4/ecl/commit/f96685267e859e9d5b4e32bac5cb57e50f1ae1ca#commitcomment-23069919

**Comment by TobiMiller** [comment]
@LorenzMeier 
I've compiled px4 master with ecl master + this PR. Result is the same. Not satisfying :( 
http://logs.px4.io/plot_app?log=f829c3ef-43b3-4eef-9ad4-dda3b543c0eb

Can anybody provide me a fmuv2 build with this PR ? I want to exclude some build mistakes on my side (builds without any error/warn).

**Comment by priseborough** [comment]
@TobiMiller Glad to hear it is now working for you. I've rebased so this branch should now include https://github.com/PX4/ecl/commit/f96685267e859e9d5b4e32bac5cb57e50f1ae1ca#commitcomment-23069919. Let me know if this now has all the patches you used for your successful test.

If you are happy with the behaviour now and area able to review the code for me, I can merge it.

**Comment by TobiMiller** [comment]
@priseborough 
I have used PR https://github.com/PX4/ecl/pull/297 and https://github.com/PX4/ecl/pull/293. Which is included in your branch now https://github.com/PX4/ecl/tree/pr-fixExtVisionFallback

**Pull request merged**
