### PR TITLE
Shared Library build

### PR DESCRIPTION
**Pull request by bugobliterator**
This PR enables standalone build for ECL's EKF library.

### CODE REVIEW

**Comment by priseborough** [comment]
@tumbili, @bugobliterator any reason why we shouldn't pull this in now?

**Comment by tumbili** [comment]
@bugobliterator @priseborough It looks good to me. Is this tested?

**Comment by dagar** [comment]
It will be tested automatically if @LorenzMeier or another admin could enable travis-ci for this repo here - https://travis-ci.org/profile/PX4

**Comment by bugobliterator** [comment]
I have already added the travis check, here is the result: https://travis-ci.org/bugobliterator/ecl/builds/110030287

**Pull request merged**
