### PR TITLE
EKF: Enable operation where mag heading is unreliable

### PR DESCRIPTION
**Pull request by priseborough**
This PR adds a parameter controlled option that enables operation in environments where the earths magnetic field is either distorted or has insufficient horizontal strength to provide a reliable yaw estimate.

It has been tested using  https://github.com/priseborough/Firmware/tree/ekfHighLatMag-wip 

and 

'make posix_sitl_default gazebo_standard_vtol'

using EKF2_MAGEF_BAD = 0, 1 or 2 and EKF2_MAG_YAWGND = 90.0 to match the simulation initial yaw.

SITL TEST RESULTS

https://logs.px4.io/plot_app?log=399b212a-0a3e-4d8c-b0a9-5256adb2678a
EKF2_MAGEF_BAD = 0 : Normal mag heading fusion in the ground with a mixture of heading and 3D fusion in the air.
screen shot 2017-10-13 at 12 31 12 pm

https://logs.px4.io/plot_app?log=be4e651e-00dc-45f2-af9e-c89ee91ddf03
EKF2_MAGEF_BAD = 1 : Static heading fusion in the ground with no fusion of mag data in air.
screen shot 2017-10-13 at 12 31 26 pm

https://logs.px4.io/plot_app?log=a13c0c5f-9278-4900-b888-d2e1d0a56ed2
EKF2_MAGEF_BAD = 2 : Static heading fusion in the ground. 3-axis mag fusion is used when selected, mag heading fusion is blocked.
screen shot 2017-10-13 at 12 31 38 pm

### CODE REVIEW

**Comment by priseborough** [comment]
Further testing is required to to ensure this works with fixed wing.

**Comment by priseborough** [comment]
Rebased and updated to add protection for unconstrained growth in quaternion variances

**Comment by priseborough** [comment]
Can be tested using https://github.com/PX4/Firmware/tree/pr-ekfHighLatMag

**Comment by priseborough** [comment]
SITL test results using  EKF2_MAGEF_BAD=2 and EKF2_MAG_YAWGND=90

https://review.px4.io/plot_app?log=6bfa1e7e-d2d6-4378-9272-a57dc1c19ee8

Low altitude flight test using small 250 class quadcopter:

https://review.px4.io/plot_app?log=54391da9-ee52-4f1a-8d05-a4578bb68cb5

**Comment by priseborough** [comment]
Further flight testing shows errors in setting EKF2_MAG_YAWGND up to 45 degrees can be tolerated before a failsafe is triggered:

Correct yaw: https://logs.px4.io/plot_app?log=1594611a-25ac-42dd-a9ba-a0c3964242b4

180 deg error: https://logs.px4.io/plot_app?log=6fcf826a-254a-4209-931f-9a262d8e1c83
-90 deg error: https://logs.px4.io/plot_app?log=e4e8e1df-d9ee-44b3-ae08-a8925945ef1a
+90 deg error: https://logs.px4.io/plot_app?log=29b9a412-2b6a-40ed-84ec-9d48c9240e63
-45 deg error: https://logs.px4.io/plot_app?log=90c0acf2-b8fe-4fb2-a048-4dee9f823b7f
+45 deg error: https://logs.px4.io/plot_app?log=f57aa7da-5b09-4fea-8275-4486979318d2

I did another longer up and away flight in windy conditions with less than 20 deg initial yaw offset, but had to switch to manual to recover later in flight. This log requires further analysis: https://logs.px4.io/plot_app?log=e9b941e1-fc8e-4ad6-8ff1-6b43dca7f6f4

**Comment by priseborough** [comment]
It looks like the problem in the last flight https://logs.px4.io/plot_app?log=e9b941e1-fc8e-4ad6-8ff1-6b43dca7f6f4 was caused by a GPS or wiring fault. The GPS receiver switches to fix type 4 at the same point in time where GPS data stops updating.

screen shot 2018-01-23 at 5 27 44 pm

The GPS is UBlox M8 that came with a pixfalcon board.

**Comment by mhkabir** [comment]
Continued in #445

**Pull request closed without merging**
