### PR TITLE
[WIP] Mag Validator

### PR DESCRIPTION
**Pull request by stephanbro**
This PR adds a data validator with specific checks for magnetometer data. The current error checking involves getting a GPS location, using lat and lon to get an inclination value from a lookup table, calculating the magnetometer's earth frame inclination, and generating an error with too high a difference between the two.

Additional changes:
* Adds the concept of "complex error" checking, which is a type specific error check and can be overridden by a derived class
* Moves `value[dimmensions]` to a protected member so it can be used by derived classes
* Check the state of complex errors when getting the validator's confidence
* Create validators based on a type enum, which currently only includes Magnetometer and Standard

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! Is this still WIP or good to go?

**Comment by stephanbro** [comment]
@LorenzMeier The concept in general is working, but I was hoping to get someone check out how I'm getting the global frame mag here: https://github.com/PX4/ecl/pull/239/files#diff-15e2f40ae61f93b78f65ab464dbfb0fdR93

I'm currently seeing large errors when I'm tilting, so I was hoping to have some one verify I'm doing things correctly.

**Comment by LorenzMeier** [comment]
@priseborough Can you pitch in here?

**Comment by priseborough** [comment]
The is nothing obviously wrong with the way you are rotating from body to earth frame given my understanding of the definition for the vehicle_attitude quaternion. Neither the vehicle_attitude topic quaternion or math library conjugate function  are adequately documented, so you could try  using the conjugate_inversed function instead. 

Comparing inclination to database value is a method that I have attempted to use before, but the presence of local ground based magnetic anomalies gave too many false alarms for the method to be useful, so the check will need to be optional with an adjustable sensitivity.

It also had the limitation that it could easily miss large errors in XY components that gave a correct horizontal field strength, but caused large heading errors at takeoff.

An alternative pre-flight magnetometer integrity check would require the user to pick up the vehicle and rotate it in heading through a minimum angle change (as detected by the IMU). It would then  check the magnetic heading innovations from the estimator. This is unlikely to be acceptable for a consumer product, but for a professional user used to following a pre-flight procedure, it would be  a more reliable method and less sensitive subject to ground based field anomalies.

**Comment by stephanbro** [comment]
Thanks for the info @priseborough. I will try to using the conjugate_inversed and see if that helps the issue I'm seeing.

I agree about the need for the check to be optional or overrideable at least, as well as the ability to tweak the window of the expected inclination. As for the sensitivity of the measurement, I've had good success in the past using an inclination check with a similar setup so I believe it at least has the potential to detect errors without being a hindrance with false alarms.

**Comment by priseborough** [comment]
I would prefer that this is not implemented in the ecl library and is moved to the PX4/Firmware/modules/commander/PreflightCheck.cpp instead where it can be used regardless of which type of estimator the codebase is running. When you do so, please provide a single parameter enabling the sensitivity to be adjusted and the check to be turned off (eg by setting the parameter to a negative number).

**Pull request closed without merging**
