### PR TITLE
EKF: Enable planes to recover from bad mag data at start of flight

### PR DESCRIPTION
**Pull request by priseborough**
Adjusts yaw by the amount of the error between GPS and EKF course if innovations are large.

### CODE REVIEW

**Comment by priseborough** [comment]
Replay testing performed using https://github.com/priseborough/Firmware/tree/pr-ekfFixedWingYawReset

**Comment by priseborough** [comment]
Can someone please provide a fixed wing log where logging starts at boot (SDLOG_MODE=1)

**Comment by priseborough** [comment]
There are some problems showing up on replay due to interaction with other reset logic that will require some further work.

**Comment by priseborough** [comment]
Issues have been resolved and testing using replay of a fixed wing log has shown the changes are able to detect and recover from a 90 degree compass yaw error.

Testing was performed by replaying a log with the compass data rotated in yaw by +90 degrees in ekf2_main.cpp by sign and axis swaps, eg:

_mag_data_sum[0] += sensors.magnetometer_ga[1];
_mag_data_sum[1] += -sensors.magnetometer_ga[0];

Here are the velocity and magnetometer innovations with good compass data and no yaw reset using GPS course required:

**GPS Velocity Innovations - Good Data**
vel innov - good data

**Magnetometer Innovations - Good Data**
mag innov - good data

Here they are with the magnetometer data rotated in yaw by +90 deg which resulted in a single yaw correction event at the start of flight 

screen shot 2017-07-07 at 9 11 27 pm

**GPS Velocity Innovations - 90 deg compass yaw**
vel innov - bad compass

**Magnetometer Innovations - 90 deg compass yaw**
mag innov - bad compass

Replaying the log using yawed compass data without the PR changes resulted in repeated GPS resets that lasted for 4 minutes before the EKF was able to recover the yaw angle:

screen shot 2017-07-07 at 9 19 10 pm

**Comment by priseborough** [comment]
I have completed further replay testing using a FW log with long straight line mission legs http://review.px4.io/plot_app?log=ed369adf-4e46-486a-bc18-14a2ed188bd0 which gives a bad magnetometer time to pull the heading round between turns. During turns the heading is corrected using the observed GPs velocity change, however during straight line segments it is only observable using the magnetometer.

This testing has shown that although this PR successfully detected and corrected magnetometer errors on launch, if flight is continues with a bad magnetometer, there is a possibility that the heading will be degraded during straight line segments sufficiently to cause a GPS rejection and reset event at the next turn. 

The following plot shows the GPS velocity innovations when the log was replayed with a 30 degree compass misalignment. The initial yaw error was corrected, however the compass error was not so great that the EKF completely ignored. Angular misalignment is the worst type of magnetometer error  because the EKF does not have the ability to learn it. 

screen shot 2017-07-08 at 10 11 51 am

Ideally the system should be alerted that a magnetometer fault has been detected and the EKF should stop using the magnetometer. As a minimum the operator should be alerted so the mission can be aborted and the plane recovered.

**Comment by LorenzMeier** [comment]
I think this is good to go. Let's get this in and the reporting on top.

**Pull request merged**
