### PR TITLE
EKF Tuning Update

### PR DESCRIPTION
**Pull request by priseborough**
- The tuning parameter defaults have been changed to a conservative set to handle larger magnetometer and IMU errors. This is an equivalent tune to the APM copter defaults and prioritises robustness to sensor error over accuracy. A tuning activity to obtain a 'performance' oriented tune will be performed later when the replay functionality is available in master.

- An error in in conversion from observation noise to observation variance in pos vel  fusion has been fixed.
- Velocity observation noise adapts with reported GPS speed accuracy.
- A separate position observation noise is used in-flight for operation without aiding. This reduces attitude errors due to manoeuvres.
- The missing magnetometer observation noise parameter has been added.

Flight testing has been completed (see following figures). The sensor error estimates are now more reactive which improves robustness at he expense of accuracy.

posne innov
velne innov
veld innov
posd innov
dangx bias
dangy bias
dangz bias
scalex
scaley
scalez
magx innov
magy innov
magz innov
mag innov
mag bias
mag earth
declination estimate
dvelz bias

### CODE REVIEW

**Comment by tumbili** [comment]
@priseborough Reviewing this!

**Comment by bugobliterator** [comment]
@priseborough It requires proper indentation, can you run this code through code check script in PX4.

**Comment by priseborough** [comment]
OK

**Comment by tumbili** [comment]
@priseborough Looks good, merging!

**Pull request merged**
