### PR TITLE
control.cpp: clean up extra code judge

### PR DESCRIPTION
**Pull request by xdwgood**
```
resetVelocity();
resetPosition();
```
always return `ture,` so we don't need judge more, just direct `resetVelocity();resetPosition();`

### CODE REVIEW

**Comment by dagar** [comment]
Logically your change looks correct, but was something else intended here?

**Comment by xdwgood** [comment]
I don't know, it may be that the previous two functions will return false in some cases, Paul should know more

**Comment by priseborough** [comment]
Can please you explain the problem change fixes and show evidence of how you have tested it? Thanks.

**Comment by xdwgood** [comment]
only code logic extra....Always return true Why do you need an if judgment?

**Comment by xdwgood** [comment]
I found out when reading the code, not from flight test.

**Comment by xdwgood** [comment]
@dagar As you said, the logical change of code is just a clean up of the code.But the problem raised by paul makes me feel confused...As long as the person who has read the code, it is easy to know that this is just a cleanup, unless he does not see the code at all. Is the clean up of ecl code not welcome?But it doesn't matter, thank you and Paul for your comments.

**Comment by priseborough** [comment]
Are you saying that it is a non functional change (dies not change behaviour) ? Have you done any testing that exercises the changed lines of code?

**Comment by xdwgood** [comment]
If this change is acceptable I can do a flight test using the H520 :smiley:

**Pull request closed without merging**
