### PR TITLE
ecl attitude_fw fix excessive body fixed turn offset

### LINKED ISSUE #181: ECL_PitchController body_fixed_turn_offset issue
The ecl pitch controller body fixed turn offset is an additional term added to the rate setpoint. 

https://github.com/PX4/ecl/blob/master/attitude_fw/ecl_pitch_controller.cpp#L153

    float body_fixed_turn_offset = (fabsf((CONSTANTS_ONE_G / airspeed) *
				  		tanf(constrained_roll) * sinf(constrained_roll)));

With large roll angles this term becomes enormous and causes problems like in this recent flight. Note the small pitch setpoint, but full elevator deflection.

ecl

I've scaled the roll, pitch, and pitch setpoints to degrees.

Clearly this should be limited, but to what? Controller roll limit?

### PR DESCRIPTION
**Pull request by dagar**
-limit body fixed turn offset contrained roll to possible
roll setpoint range
-fixes #181

### CODE REVIEW

**Comment by dagar** [comment]
This fixes the current usage in PX4, where inverted flight isn't yet possible and the max roll is going to be set to something reasonable.

**Comment by LorenzMeier** [comment]
Good to merge / tested?

**Comment by tumbili** [comment]
@dagar While you are at it, could you please check if this constrain is correct?
https://github.com/PX4/ecl/blob/81d891a58c7e38296f0b22e7e2d29fd29cbab3c8/attitude_fw/ecl_pitch_controller.cpp#L142
Shouldn't the arguments be swapped?

**Comment by dagar** [comment]
@tumbili Yes, but now I'm thinking I should probably fix the same numerical problem if I'm going to touch the inverted section at all.

**Pull request merged**
