### PR TITLE
Addressed C99 compiler issues of initializing variables in header and…

### PR DESCRIPTION
**Pull request by waltjohnson**
unused included statements.  Also 	isfinite() is not part of the math class, rather the math.h header file.

### CODE REVIEW

**Comment by waltjohnson** [comment]
Lorenz.  The variable initialization I removed from the estimator_interface.h (lines 263-267) already exist in estimator_interface.cpp (lines 55-58 and 71).

**Comment by LorenzMeier** [comment]
Thanks! Could we generalise the isfinite handling into a header, using this logic?

https://github.com/PX4/ecl/blob/e3b9800cac459e7c279395c18191a872f465f848/EKF/ekf.cpp#L45-L52

**Comment by waltjohnson** [comment]
Yes, we can generalize isfinite()...

**Comment by LorenzMeier** [comment]
@priseborough This looks good to me, its just changing the API from C++11 (which is kinda new) to C99.

**Pull request merged**
