### PR TITLE
EKF: Enable operation where mag heading is unreliable

### PR DESCRIPTION
**Pull request by mhkabir**
Rebased version of https://github.com/PX4/ecl/pull/335.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@priseborough Good to go?

**Comment by priseborough** [comment]
We need to do some testing. I didn't have tine to do any last week.

**Comment by priseborough** [comment]
It failed to commence using GPS on my limited testing this afternoon. Test used https://github.com/priseborough/Firmware/tree/ekfHighLatMag-wip with EKF2_MAG_BAD=1 and EKF2_MAG_YAWGND=90

I will investigate further.

**Comment by priseborough** [comment]
I've rebased and using latest PX4/Firmware master was able to arm in POSCTL. Will test further tomorrow. 

I think it makes sense to try and integrate this better into the logic that has been added to enable a non-magnetomer mode for indoor use which is selected using the EKF2_MAG_TYPE parameter.

The EKF2_MAGEF_BAD parameter added by this PR is going to be confusing, so I will try to add it as another option selected by EKF2_MAG_TYPE.

Also the movement check used on ground when EKF2_MAG_TYPE = 4 which enables the vehicle to be picked up and moved can also be used to avoid the restriction imposed by this PR which requires the vehicle to be not rotated in yaw when on ground.

**Comment by priseborough** [comment]
Closing this until it is reworked to integrate with the _mag_use_inhibit flag and EKF2_MAG_TYPE = 4 behaviour.

**Pull request closed without merging**
