### PR TITLE
Pr ekf yaw cov reset

### PR DESCRIPTION
**Pull request by LorenzMeier**
Work in progress started in response to https://github.com/PX4/ecl/issues/541. Refer to https://github.com/PX4/ecl/issues/541 for previous discussion and testing.

### CODE REVIEW

**Comment by priseborough** [comment]
@CarlOlsson  I have implemneted another approach to simplify the way fuseDeclination() is only called, either immediately before fuseMag() if it hasn't been called since the last yaw reset or immediately after if _control_status.flags.mag_dec is true. This will simplify the overall logic.

See commit: 
https://github.com/PX4/ecl/pull/556/commits/614011a377aaa4c65410e22a262ff8983ac9481f

See SITL log: https://logs.px4.io/plot_app?log=1bd258f2-7bef-4b9a-8cc8-c13190fb89c1

**Comment by priseborough** [comment]
The fuseDeclination() function was being called unnecessarily on each re-entry into 3-axis fusion when auto switching was enabled. Fixed here: 
https://github.com/PX4/ecl/pull/556/commits/a6506405749aecefa090d386f26397224ad487d3

**Comment by priseborough** [comment]
MC flight test logs. A ground fixed bar magnet was placed near the vehicle to swing the magnetic heading prior to takeoff and trigger a significant inflight yaw reset.

https://logs.px4.io/plot_app?log=233b88b5-0165-44c3-8106-d1e0069f7e8f
https://logs.px4.io/plot_app?log=9e19c505-eeb6-4c71-9a10-e69586a6185d

Problem with these logs is that heading innovations are logging as zero. After this has been resolved, further testing with logging from boot will be performed with a magnet placed on the airframe to swing magnetic heading and test the ability of the EKF to learn the body fixed mag field error when toilet bowling starts.

**Comment by LorenzMeier** [comment]
@bkueng I think @priseborough has a logging issue here - could you follow up on PX4 slack? Thanks!

**Comment by priseborough** [comment]
Logging issue has been resolved. it was a problem with my log file processing.

**Comment by priseborough** [comment]
@bkueng The ekf2 replay appears to be running to be running, but the generated log only contains headers and parameters, not data. I am working from v1.9.0-beta1 at commit 504372f plus the commit to point to the ecl pr-ekfYawCovReset branch at commit 1977b11. The same problem also occurs with unmodified v1.9.0-beta1 code.

Input log: 
https://logs.px4.io/plot_app?log=bc2422ae-8a92-46b3-ba24-a848fdf65278

Output log:
https://logs.px4.io/plot_app?log=bc778edd-247e-4c29-8306-e799db2a12b1

Console output:
screen shot 2019-01-28 at 5 15 55 pm

**Comment by priseborough** [comment]
@bkueng I've done done some further investigation and have confirmed that the ekf2 module is running this line https://github.com/PX4/Firmware/blob/master/src/modules/ekf2/ekf2_main.cpp#L1758 but the uORB data is not being detected by the logger module here: https://github.com/PX4/Firmware/blob/master/src/modules/logger/logger.cpp#L1157 because log_message_updated always returns false.

**Comment by mhkabir** [comment]
Does this also handle https://github.com/PX4/ecl/issues/557?

**Comment by priseborough** [comment]
> Does this also handle #557?

@mhkabir To be determined.

**Comment by priseborough** [comment]
Commit https://github.com/PX4/ecl/pull/556/commits/614011a377aaa4c65410e22a262ff8983ac9481f
has been added to prevent the problem observed in previous testing where large magnetometer errors could the estimated NE field vector to collapse in length and flip sign, preventing the filter recovering its yaw with subsequent data. These tests successfully demonstrated the effectiveness of the patch.

As per previous testing a magnet was attached to the vehicle and it was aligned and flown initially in POSCTL mode at four initial headings relative to magnetic North:

**Yaw 000 :** https://review.px4.io/plot_app?log=d3aaa146-eab7-460d-8e77-0af368a961d5
Yaw error at alignment was small due to horizontal component of magnetic disturbance being aligned with the earth field. Velocity innovations reduced during flight as the yaw error was removed:

screen shot 2019-01-30 at 3 33 57 pm

Horizontal strength and declination of estimated earth field were converging to reasonable values:

screen shot 2019-01-30 at 3 36 01 pm

**Yaw 090 :** https://review.px4.io/plot_app?log=b3cab03a-d5f9-4d39-b738-fd08eaf86483
Initial yaw error induced was ~45deg which induced noticeable toilet bowling and velocity innovations in excess of 1.75 m/s, but not enough to trigger a  failsafe. The EKF recovered.

screen shot 2019-01-30 at 3 38 25 pm

Horizontal strength and declination of estimated earth field were converging to reasonable values:

screen shot 2019-01-30 at 3 39 04 pm

**Yaw 180 :** https://review.px4.io/plot_app?log=2ed74812-d284-4e94-836c-8e1ca71fcae2
Initial yaw error induced was >120 deg which induced a flyaway and triggering of the failsafe and reversion into ALTCTL mode. The EKF recovered after two resets to GPS.

screen shot 2019-01-30 at 3 42 28 pm

Horizontal strength and declination of estimated earth field were converging to reasonable values:

screen shot 2019-01-30 at 3 43 08 pm

Yaw 270 : https://review.px4.io/plot_app?log=875767b2-174d-4cd5-ba3f-d413cc0075b7
Initial yaw error induced a divergent toilet bowl motion and triggering of the failsafe and reversion into ALTCTL mode. The EKF recovered after one reset to GPS.

screen shot 2019-01-30 at 3 44 33 pm

Horizontal strength and declination of estimated earth field were converging to reasonable values:

screen shot 2019-01-30 at 3 46 25 pm

**The magnet was reversed to reverse the sign of the initial offset and the tests repeated**

Results were similar taking into account the changed magnetic offset.

**Yaw 000 :** https://review.px4.io/plot_app?log=d6925cc4-ae9a-4e08-8f87-c5d7dd4bec03
Temporary loss of navigation requiring two resets.  
screen shot 2019-01-30 at 3 50 29 pm

Field estimation was degraded, but stayed within limits:
screen shot 2019-01-30 at 3 50 58 pm

**Yaw 090 :** https://review.px4.io/plot_app?log=7b0c717c-74d1-44e8-9644-47c877125211
Temporary loss of navigation triggering a failsafe and requiring one reset.
screen shot 2019-01-30 at 3 52 26 pm

Field estimates were within limits and converging to reasonable values
screen shot 2019-01-30 at 3 53 04 pm

**Yaw 180 :** https://review.px4.io/plot_app?log=4e9e3a14-3feb-4b3d-bcde-96bd5685d965
Initial yaw error not enough to trigger a failsafe or noticeable change to flight characteristics
screen shot 2019-01-30 at 3 54 31 pm

Field estimates were within limits and converged rapidly to reasonable values
screen shot 2019-01-30 at 3 55 08 pm

**Yaw 270 :** https://review.px4.io/plot_app?log=a22f4a9b-45ef-4bdf-b597-1a17ca052b14
Some initial toilet bowling. No failsafe.
screen shot 2019-01-30 at 3 56 56 pm

Field estimates were within limits and converged rapidly to reasonable values
screen shot 2019-01-30 at 3 57 58 pm

**Comment by priseborough** [comment]
@dagar are you able to provide some advice on how to resolve the CI error: http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fecl/detail/pr-ekfYawCovReset/16/pipeline/

**Comment by dagar** [comment]
> @dagar are you able to provide some advice on how to resolve the CI error: http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fecl/detail/pr-ekfYawCovReset/16/pipeline/

Working on a proper fix for Jenkins here - https://github.com/PX4/ecl/pull/564

**Comment by CarlOlsson** [comment]
Tried to test the reset logic for fw in SITL but always get
```
[Err] [gazebo_mavlink_interface.cpp:1018] poll timeout
[Err] [gazebo_mavlink_interface.cpp:1018] poll timeout
[Err] [gazebo_mavlink_interface.cpp:1018] poll timeout
[Err] [gazebo_mavlink_interface.cpp:1018] poll timeout
[Err] [gazebo_mavlink_interface.cpp:1018] poll timeout
[Err] [gazebo_mavlink_interface.cpp:1018] poll timeout
```

**Comment by priseborough** [comment]
@CarlOlsson I was able to run it in my Ubuntu 16.04 build environment and confirm that the patch 
https://github.com/PX4/ecl/commit/54ebf6483bdfcfb5a9a011d7cdf92a122b1435e8 fixes 
https://github.com/PX4/ecl/issues/557. Note that for some reason the value of EKF2_MAG_TYPE has been set to 1 for SITL simulations, so that had to be changed to 0 which is the default behaviour. A printf statement was inserted to confirm that the realignYawGPS() function was being called.

screen shot 2019-01-31 at 7 52 05 am

Log is here: https://review.px4.io/plot_app?log=ac6f88f8-a8b6-4a2d-8e3e-e70aadc604b7

**Comment by LorenzMeier** [comment]
@priseborough Could you approve this PR once you consider it complete and ready for on-vehicle flight testing?

**Comment by dagar** [comment]
Could everyone please converge on testing the PX4/Firmware side ecl update? https://github.com/PX4/Firmware/pull/10986

**Pull request merged**
