### PR TITLE
Fixed wind estimation

### PR DESCRIPTION
**Pull request by vvranjek**
Wind estimation wasn't working for me so I fixed it.  I am not completely sure if I've done the whole thing correctly, since I am new to this code and only spent a day on it, but I am sure that the math/physics behind wind estimation is now correct. For example, I am not sure what is  `_control_status_prev.flags.wind` and what this does:
```
// initialise diagonal of covariance matrix for the wind velocity states
		for (uint8_t index = 22; index <= 23; index++) {
			P[index][index] = sq(5.0f);
		}
```
But wind estimation works for me on the pixhawk.

Cheers!

### CODE REVIEW

**Comment by tumbili** [comment]
@vvranjek The code you have modified is just taking care of the initialization of the wind states.
The actual estimation of wind speed is happening when airspeed measurements are fused in.

**Comment by vvranjek** [comment]
What does ' initialization of the wind states' mean? Where is the continuous wind calculation done then?

I dont't understand, was wind estimation working for you before? It didn't for me but now it does.

**Comment by tumbili** [comment]
@vvranjek Everything that you need is implemented in #183 
Once wind estimation starts the wind states are initialized with the same formula you have  been using (zero side slip assumption). After that wind states are updated via fusion of airspeed measurements.
You can find the relevant code here https://github.com/PX4/ecl/blob/master/EKF/airspeed_fusion.cpp#L71

**Comment by tumbili** [comment]
@vvranjek It would be cool if you could test fly #183 and give feedback on that (and share the logs).
@CarlOlsson Has already been flying it but his flight was very short.

**Pull request closed without merging**
