### PR TITLE
attitude_fw delete unused and cleanup

### PR DESCRIPTION
**Pull request by dagar**
PX4 side: https://github.com/PX4/Firmware/pull/7855

### CODE REVIEW

**Comment by dagar** [comment]
I slipped in some minor style cleanup in EKF. sideslip_fusion.cpp indenting was very wrong and quite difficult to read. I used PX4 astyle, but didn't limit line lengths and ignored the compacted math sections.

**Comment by dagar** [comment]
I'll break out the EKF style change.

**Comment by LorenzMeier** [comment]
@dagar @priseborough Could you coordinate on this one?

**Comment by dagar** [comment]
Rebased on top of EKF style cleanup.

Changes to attitude_fw in this PR
 - remove dead yaw coordinated turn methods
 - max_rate check change from `_max_rate > 0.01f` to `_max_rate >= 0.0f`, this allows you to disable a controller by setting the max rate to 0
 - replace PX4_ISFINITE with ISFINITE included in ECL
 - initialization cleanup
 - mark virtuals as override and classes as final (c++11)

Tested as part of https://github.com/PX4/Firmware/pull/7855.

**Pull request merged**
