### PR TITLE
EKF: Improve height reset behaviour

### PR DESCRIPTION
**Pull request by priseborough**
Addresses #96 and #91 

Has been flown in SITL for normal operation and bench tested for a GPS height timeout

Height reset recovery from each of the three modes (Baro, GPS and range finder) needs to by tested. I have tried using SITL, but it does not support adding offsets to sensor outputs.

### CODE REVIEW

**Comment by priseborough** [comment]
Failed bench testing with a manual offset added to the Z accelerometer offset to induce a loss of height fusion.

**Comment by tumbili** [comment]
@priseborough Looked at this and generally looks good. I haven't seen any use of "_hgt_sensor_offset", is that missing? I would expect this value to be set when we are switching between the height sensors to maintain consistency.

**Comment by priseborough** [comment]
_hgt_sensor_offset is included  to allow for the height to be maintained after a reset if required. Currently there are no resets that use it, however I have left it in because the requirements for reset behaviour when using different sensors could change when we do more testing.

**Comment by priseborough** [comment]
I have completed testing using the replay and confirmed sensible switching and reset behaviour when using GPS and baro.

**Pull request merged**
