### PR TITLE
Add Sideslip function

### PR DESCRIPTION
**Pull request by CarlOlsson**
Adds the sideslip function but no functionality regarding when to fuse it etc

### CODE REVIEW

**Comment by CarlOlsson** [comment]
@tumbili is this ok to merge? It just adds the sideslip function but not the logic, would be nice to merge it and avoid future rebasing

**Comment by CarlOlsson** [comment]
Goes together with this
https://github.com/PX4/Firmware/pull/4481

**Comment by LorenzMeier** [comment]
@priseborough Good to go?

**Comment by priseborough** [comment]
Pull requests for that contain significant changes (which includes new fusion methods) should be accompanied with test evidence (flight or SITL logs).

**Comment by CarlOlsson** [comment]
Hi Paul. I definitely agree, I will supply flight tests and post logs etc. However, since the function isn't called anywhere yet I thought that we could merge it even without that. I can also close this one and create a new when everything is ready if that is preferable?
And thanks for reviewing!

**Comment by priseborough** [comment]
Carl, I would prefer to wait until we have something that can be tested. Let's organise a Skype call to discuss the control logic requirements.

**Comment by CarlOlsson** [comment]
Ok perfect. Then I will close this pr and create a new cleaner one with logs + plots

**Pull request closed without merging**
