### PR TITLE
EKF: Accuracy Improvements

### PR DESCRIPTION
**Pull request by priseborough**
Improves stability during sustained high angular rates and for operation with vehicles that do not have a preferred orientation (eg tailsitters). Needs to be used in combination with https://github.com/PX4/Firmware/tree/ekf2AccuracyImprovement. Contains:

- Reworked derivation with direct quaternion attitude parameterisation.
- Removes scale factor states and adds X and Y accel bias states.
- IMU delta velocity bias learning can be optionally turned off
- Fixes timing error in application of learned IMU errors
- Optimises gains in output complementary filter
- Preliminary retune of parameters

The error vector parameterisation could not be reworked in the time available to provide the required high spin rate stability, so the attitude parameterisation has been changed to a direct quaternion form. Testing has shown that initial alignment remains acceptable provided a gravity vector is available to give an approximate initial tilt.

Scale factor states have been removed because gyro nonlinearities and change in scale factor with temperature meant they could not be learned reliably.

The X and Y accel bias states were added to support operation with tail-sitters and other applications where there is not a preferred orientation.

TODO: 

Confirm correct operation with airspeed data (replay logs required)

**Flight Test Results**

Data gathered on a 250 quad with pix-racer board on isolation mounts. Sustained rapid yaw spins and rapid velocity changes in attitude control mode were performed. 

**Euler Angles**

roll pitch
yaw

**Innovations**

Barometer
posd innov

GPS North East Position
posne innov

GPS Down Velocity
veld innov

GPS North East Velocity
velne innov

Magnetometer X-axis
magx innov

Magnetometer Y-axis
magy innov

Magnetometer Z-axis
magz innov

**IMU Bias Learning**

delta angle bias
del ang bias

delta velocity bias
del vel bias

**Magnetic Field Learning**

Declination Angle 
declination

Magnetometer Bias
mag bias

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@priseborough @tumbili What is the integration state of this?

**Comment by priseborough** [comment]
I have completed flight testing with GPS and Baro sources today and am happy with the tune. I now need to get some replay logs with optical flow and range sensors on a copter and a replay log from a plane to test it on.

If they both are OK, then I will merge it because the attitude reference has been very solid and there have been no problems with sustained high yaw rates.

**Comment by priseborough** [comment]
Rebased

**Comment by tumbili** [comment]
@LorenzMeier @priseborough I wanted to give this a go on Snapdragon but unfortunately the DSP crashes. I did not spot anything obvious in the changes and the diff to master is just ekf2 related.
I flew this implementation on the 450 and it felt really good, splendid altitude performance on baro and range.

**Comment by priseborough** [comment]
Indoor flight test in attitude control mode with GPS and baro fusion enabled.

http://logs.uaventure.com/view/dGir3YWsaKqiZ4rZjJ3mT3

**Comment by priseborough** [comment]
http://logs.uaventure.com/view/tX9E2QD8X6f3GW8BNyX3T3

**Comment by priseborough** [comment]
Optical flow and range finder testing:
http://logs.uaventure.com/view/eLjc3x5ctCJeDY5pmZgBpf

**Comment by priseborough** [comment]
@CarlOlsson Do you have a plane relay log with airspeed measurements that I can test this on?

**Comment by CarlOlsson** [comment]
Unfortunately I haven't been able to record a replay log. I don't know what the problem is but will send you one as soon as it works, hopefully tomorrow

**Comment by priseborough** [comment]
Plots generated using replay of optical flow, mag and range finder data. https://github.com/PX4/ecl/pull/117/commits/00973d62156d7627e9e619c4e49c9a4e432fb2d8 has improved height tracking.

dang bias
dvel bias
flowx innov
flowy innov
hagl innov
posd innov
yaw innov

**Comment by priseborough** [comment]
Flight test using GPS and baro on a Pixracer board in a indoor environment with GPS errors and magnetic anomalies. http://logs.uaventure.com/view/BSKjYGVGeihg4Lwxd9FN2M

BARO FUSION

posd innov

GPS FUSION

posne innov
velne innov
veld innov

IMU BIAS ESTIMATION

dang bias
dvel bias

MAGNETIC FIELD ESTIMATION

mag bias
mag angles

MAGNETOMETER FUSION

magx innov
magy innov
magz innov

OUTPUT FILTER TRACKING
velne tracking
posne tracking
output filter tracking

**Comment by tumbili** [comment]
@priseborough Tested on a 450 with good performance:
no replay log:
http://logs.uaventure.com/view/irUEtdvTdbLLmZR6P9MMCG

replay log (with heading fusion always):
http://logs.uaventure.com/view/j3EKm989ryewHsL2Y5Zhin

**Comment by priseborough** [comment]
OK - those logs look good, so rather than delay waiting for plane flight logs, I will pull the PR in as there is some other work that is blocked from starting until it goes in.

**Pull request merged**
