### PR TITLE
EKF: Add missing optical flow ground motion protection

### PR DESCRIPTION
**Pull request by priseborough**
Motion compensated optical flow rates are supposed to be zeroed if flow data is failing validity checks when on ground. This was not being done in the code. The comments and logic have been amended to be consistent and make the design intent clearer.

### CODE REVIEW

**Comment by mhkabir** [comment]
This broke optical flow. The EKF now diverges if optical flow aiding is enabled. Haven't investigated further yet.

Replay log : 
https://review.px4.io/plot_app?log=09958de4-6654-4585-a0b0-eab8a1e4ca66

There is a bad timestamp in the log, which causes the weird plot visualisation, but it should  be fine otherwise.

**Comment by priseborough** [comment]
@mhkabir I reviewed the code and found a potential issue which has been fixed by 
https://review.px4.io/plot_app?log=09958de4-6654-4585-a0b0-eab8a1e4ca66 however the reported flow quality on your log is always above the minimum so this should not have affected your setup.

With this fix, optical flow is working well on SITL 'make posix gazebo_iris_opt_flow'

I was unable to get replay working on your log using upstream master with or without the fix. The range data and flow data timestamps cover different ranges and there are lots of differences in message formats reported by replay. You need to get your timestamp issue fixed and provide data recorded with up to date message definitions.

**Comment by priseborough** [comment]
The flow data doesn't start until 34 seconds.

**Comment by mhkabir** [comment]
@priseborough Here is another log where is EKF diverges on the ground after some moving around: https://logs.px4.io/plot_app?log=ea18fc88-8ce5-4382-ab62-35a9a0d015f3. It's pretty reproducible and happens sometimes even without any motion while on the ground.

For replay, you will need to be on v1.8.

**Comment by mhkabir** [comment]
I am able to replay the above log successfully, and the EKF diverges with optical flow enabled, but does not with optical flow disabled.

**Comment by priseborough** [comment]
There is a period just after motors start where there are repeated rapid accel transients and high angular rates. It looks like the vehicle is rapidly bouncing between ground contact points. This motion is causing the estimator velocities to diverge. Setting EKF2_OF_QMIN to a larger value to force use of zero motion compensated flow rates did not help, so another strategy is needed to handle the characteristics of this hardware.

screen shot 2018-09-03 at 7 57 24 am

Will investigate further.

**Comment by mhkabir** [comment]
I found the fix actually. From the log, flow use is successfully inhibited by the "motion excessive" tests, however the check for no fusion over a time period is incorrect. 

Will push to a branch and ask for review.

**Comment by priseborough** [comment]
That makes sense. The angular rates and accelerations seen during takeoff were high. I've reviewed, approved and merged the PR.

**Pull request merged**
