### PR TITLE
Changed airspeed innovation gate to 10

### PR DESCRIPTION
**Pull request by CarlOlsson**
Will test this later in the week

### CODE REVIEW

**Comment by priseborough** [comment]
If the gate needs to be this big, then there is something wrong elsewhere in the filter tuning. We want this to be able to reject measurements if the pitot tube blocks and the airspeed goes close to zero. Changes to this and the other defaults airspeed fusion  parameters need to be validated using replay of flight logs with airspeed failure injected to ensure that it will not cause loss of position or attitude reference.

**Comment by CarlOlsson** [comment]
Thanks for the comments, I changed it because I picked the first value arbitrary. What innovation gate would you start with as default?

**Comment by priseborough** [comment]
5-sigma is a good starting point

**Comment by LorenzMeier** [comment]
@CarlOlsson Could you please address the comments here or close?

**Comment by CarlOlsson** [comment]
innovation gate changed to 5 and rebased

**Pull request merged**
