### PR TITLE
EKF: Revert "Make covariance matrices of type matrix::SquareMatrix"

### PR DESCRIPTION
**Pull request by priseborough**
Fixes https://github.com/PX4/ecl/issues/745

Log used for replay testing here: https://logs.px4.io/plot_app?log=e7623a61-20fc-4179-b048-38abe9ac6c6e

Log from replay using master at commit b399698: https://logs.px4.io/plot_app?log=66a8dfba-c1c2-4ea2-81fc-bbc5836d2c5b

Summary Plot
Screen Shot 2020-02-12 at 11 03 07 am

Log from replay of this PR using PX4/Firmware branch https://github.com/priseborough/Firmware/tree/debug_using_ecl_master: https://logs.px4.io/plot_app?log=6daac421-cc73-4937-82b0-f33ba077c20e

Summary Plot
Screen Shot 2020-02-12 at 11 12 43 am

There is a change the external interface access to the covariance data - see https://github.com/PX4/ecl/compare/master...priseborough:debug_using_ecl_master?expand=1#diff-0be2b3391d4586f3ecc561669eee2529. This could probably be avoided. Suggestions are welcome.

The matrix::SquareMatrix changes can then be reintroduced starting with non-functional changes and using the sensor replay capability added by https://github.com/PX4/ecl/pull/717 to verify output.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Habe you seen the code style check failures?

**Comment by priseborough** [comment]
Yes, and there are also failures of the build for the sensor simulator that I need to follow up. I need to update my build environment before I can run the style checker.

**Comment by priseborough** [comment]
This PR has broken the test program which relied on the square matrix accessor functions, so those interfaces will need to be restored.

**Comment by bresch** [comment]
I have the tests fixed and I'll fix format now

**Comment by bresch** [comment]
replaced by #747

**Pull request closed without merging**
