### PR TITLE
Check change indication on PR

### PR DESCRIPTION
**Pull request by kamilritz**
We missed to check the change indication on open PRs.

### CODE REVIEW

**Comment by mhkabir** [comment]
Shouldn't we do it on both push and pull request?

**Comment by kamilritz** [comment]
We could. That would be helpful for running the checks before opening a PR. The downside is that each test is listed twice on the PR. Once for the one running on the PR and once for the one that was running on push.

**Comment by mhkabir** [comment]
Yeah, but I think it's acceptable, because we want it to run on master on pushes/when PRs are merged.

**Comment by kamilritz** [comment]
@mhkabir  This should be exactly what we want. See newest commit.

**Pull request merged**
