### PR TITLE
EKF: Revert "Make covariance matrices of type matrix::SquareMatrix"

### PR DESCRIPTION
**Pull request by bresch**
replaces https://github.com/PX4/ecl/pull/746

### CODE REVIEW

**Comment by jkflying** [comment]
Reassuring to see that the 'change indicator' test is working as expected. I guess this would have been caught if the change indicator was in earlier.

**Comment by bresch** [comment]
@jkflying Yes, and it will be really useful when we'll have to re-apply the patch

**Comment by bresch** [comment]
Made a flight test and everything seems fine:
https://logs.px4.io/plot_app?log=ecb397a9-815d-4600-8b6d-80b7724a6f29
newplot(2)

**Comment by jkflying** [comment]
Just an idea, if you make a covariances_diagonal() compatible with the old API, then you won't need a firmware PR. Especially since this is hopefully a temporary fix.

**Comment by bresch** [comment]
replaced by https://github.com/PX4/ecl/pull/749

**Pull request closed without merging**
