### PR TITLE
remove superfluous elseif

### PR DESCRIPTION
**Pull request by bartslinger**
Fixes https://github.com/PX4/ecl/issues/430

### CODE REVIEW

**Comment by bartslinger** [comment]
Actually just realized that the entire check is superfluous, because the only four possibilities are already covered in the if-statement. What do you think @ChristophTobler ?

**Comment by ChristophTobler** [comment]
>Actually just realized that the entire check is superfluous, because the only four possibilities are already covered in the if-statement.

True. Can you update the PR accordingly?

**Comment by ChristophTobler** [comment]
@bartslinger Can you please resolve the conflicts?

**Comment by bartslinger** [comment]
Also added `_control_status.flags.ev_hgt = false;` because otherwise you could end up in a situation where both `baro_hgt` and `ev_hgt` are set to true. I assumed that that's not desirable.

**Comment by mhkabir** [comment]
@priseborough Can you review this please?

**Pull request merged**
