### PR TITLE
fw multiply integrator gain in loop

### PR DESCRIPTION
**Pull request by dagar**
Otherwise the transition can be quite abrupt when tuning.

### CODE REVIEW

**Comment by dagar** [comment]
Can we merge this? I can create a before/after log if desired.

**Comment by dagar** [comment]
@tumbili Can we merge this? I can create a before/after log if desired.

**Comment by tumbili** [comment]
@dagar Thanks, looks like that I gain was there for nothing :-D

**Comment by tumbili** [comment]
@dagar Could you do a PR for the PX4 side as well?

**Comment by dagar** [comment]
Sure, do you just keep it pointed at the latest commit? Do you perform any basic testing for accepting a new version of ecl on the PX4 side?

**Pull request merged**
