### PR TITLE
Pr check stuck rng

### PR DESCRIPTION
**Pull request by ChristophTobler**
@priseborough Is this somewhat what you were thinking of (https://github.com/PX4/ecl/pull/307#issuecomment-316368891)?

### CODE REVIEW

**Comment by ChristophTobler** [comment]
[Here](http://logs.px4.io/plot_app?log=3465176e-fc75-4ef3-b70a-fd1fdc8b033a)'s a SITL log with your described range finder behavior.

**Comment by priseborough** [comment]
@ChristophTobler  Yes, that's representative of the type of fault I have seen before. Now in theory we could get a false positive If the range finder went out of range and then the vehicle flew over a flat roof and hovered there, however that is an edge case and eventually vertical movement of the vehicle would cause the variance check to pass.

@CarlOlsson Does this look sensible to you - I think it would have prevented the terrain estimation error we were looking at the other day.

**Comment by ChristophTobler** [comment]
>Now in theory we could get a false positive If the range finder went out of range and then the vehicle flew over a flat roof and hovered there, however that is an edge case and eventually vertical movement of the vehicle would cause the variance check to pass.

I thought of that as well. But not using good range data for a short while is less dangerous as using false data, I think.

**Comment by priseborough** [comment]
Agree.

**Comment by CarlOlsson** [comment]
I will review as soon as I get some time in the coming days!

**Comment by CarlOlsson** [comment]
I have tested this is SITL now. However I could not reproduce the intended behavior. 
image
15s: The vehicle takes off
20s: The vehicle reaches 10 m altitude
25s: The range finder suddenly starts to output a fixed value of 2m. The hagl innovations goes to 8 m. The hagl_test_ratio spikes. The hagl_innov_variance starts to grow since the ekf is rejecting the range measurements.
48s: The EKF2_RNG_GATE param is increased to speed up the test until hagl_test_ratio is below one.
50s: The hagl_test_ratio goes below one and the range finder measurements are not rejected anymore. The dist_bottom_valid flag becomes 1 and dist_bottom becomes 2.

-> This should not have happened, the ekf should reject the range sensor since it is stuck on 2 m. Is this a correct interpretation?

**Comment by priseborough** [comment]
@CarlOlsson There needs to have been no range finder data for more than 10 seconds before the check will operate - see line 954 in control.cpp. The intended scenario is a vehicle coming back within range from up and away flight.

**Comment by ChristophTobler** [comment]
@CarlOlsson Sorry for the late response but I was on vacation.
@priseborough is right. There needs to have been no range finder data (invalid data) for more than 10 seconds. Your test scenario would be like flying over a house with a flat roof where it should not be rated as stuck.

**Comment by CarlOlsson** [comment]
Ok, yes you are right that the failure case we have seen is that the sensor gets stuck if it is out of range not suddenly when in range. So makes sense, thanks @ChristophTobler for the implementation!

**Pull request merged**
