### PR TITLE
Create total energy control system implementation

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is a new, clean and streamlined variant of the mathematical derivation created by Paul Riseborough a few years ago.

### CODE REVIEW

**Comment by dagar** [comment]
Should we get rid of the vertical velocity complementary filter?

**Comment by LorenzMeier** [comment]
The filter is not just filtering the input, but also damping the control response. So we would need extensive testing to figure out if the raw estimation output is suitable. My guess is that it's not because in the presence of vibration the state estimate needs to track the vibration state closely, but the controller should not.

**Comment by dagar** [comment]
I was referring to this part that's skipped if we pass in a valid vz. https://github.com/PX4/ecl/blob/tecs_cleanup/tecs/tecs.cpp#L99-L114

Currently fw_pos_control_l1 only runs with global position updates (vz always valid), so when used within PX4 this particular complementary filter isn't used.

**Comment by dagar** [comment]
Rebased to fix CI.

**Pull request merged**
