### PR TITLE
ekf: Add override specifiers

### PR DESCRIPTION
**Pull request by bresch**
Simply add the `override` specifier whenever possible.

### CODE REVIEW

**Comment by dagar** [comment]
Build failures PX4/Firmware side. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-compile_mac/detail/ecl_PR-658/1/pipeline

You should get roughly the same results on linux with clang.

`CC=clang CXX=clang++ make px4_sitl_default`

**Comment by bresch** [comment]
@dagar Thanks, I had to add `-Werror=suggest-override` in the CMakeLists of ecl to throw the error.

**Comment by bresch** [comment]
@dagar Done, can you check again please?

**Comment by dagar** [comment]
It's not tightly integrated, but PX4Buildbot automatically creates branches off of PX4/Firmware to test PX4/ecl.

https://github.com/PX4/Firmware/branches/active

image

In https://github.com/PX4/Firmware/tree/ecl_PR-658 everything is now passing (except an unrelated intermittent catkin failure).

**Comment by bresch** [comment]
@dagar Cool, I didn't know that

**Pull request merged**
