### PR TITLE
Switch to Github Action for CI

### PR DESCRIPTION
**Pull request by kamilritz**
This PR aims to replace jenkins CI with Github Actions.

TODO:
- [x] Port and setup code cov
- [x] Setup credentials as secret
- [x] Port Firmware build test
- [x] ~~Port doxygen if needed~~ if needed can be added later
- [x] Remove jenkin & travis
- [ ] All test except for `Firmware build test` should be required for merge.

https://github.com/PX4/ecl/issues/713

### CODE REVIEW

**Comment by dagar** [comment]
I've added the CODECOV_TOKEN as a PX4/ecl secret.

The Firmware build test is kind of a weird one we can come back to later.

**Comment by kamilritz** [comment]
@dagar This is ready know

**Comment by dagar** [comment]
Actually it looks like we should leave travis-ci (at least for now) until equivalent lazy integration with Coverity exists.

**Comment by kamilritz** [comment]
@dagar left the travis-ci for now

**Pull request merged**
