### PR TITLE
EKF: add support for external vision data

### PR DESCRIPTION
**Pull request by priseborough**
Replaces #101 

@devbharat Can you please test this and report back. Before I merge this PR I need  a matching PR on the PX4/Firmware side that includes the changes to logging and replay so the vision aiding can be tested, debugged and tuned off-line.

### CODE REVIEW

**Comment by devbharat** [comment]
Will test it today

**Comment by devbharat** [comment]
Flight tested it yesterday, works OK. Observed that ekf2 altitude initialization was closer to EV altitude when ev data was being provided before ekf2 started. 

Still issues in that ekf2 state position oscillates quite more than ev position which is rock steady. Also, in freak cases when ev diverges (drifts away smoothly to very high values) it takes ekf2 down with it.

**Comment by devbharat** [comment]
Outdoor flight testing it today, will report back with logs.

**Comment by priseborough** [comment]
OK, we need to get the EV data into the replay so we can tune and fix off-line

**Comment by devbharat** [comment]
@priseborough It'd be a lot of help if you could look at my log files for vision fusion. I have the following issues:
  - local position in x and y take a long time (>10 s) to converge to external vision based x y position estimate at initialization. 
  - local position z initializes well, but on very aggressive motions, ekf2's height estimate diverges even though external vision is sending in 'decent' non diverging height values. 
  - local position x and y oscillate about the external vision xy values (which are accurate) when yawing

Whats the preferred way to share log files with you ? http://logs.uaventure.com/ has issues.

**Comment by devbharat** [comment]
Sending Log via wikisend. You can trust it, I tested the link
http://wikisend.com/download/174296/log001.px4log

The logs are for small handheld test. Initially aggressive up-down motion in altitude. Random high rate rotations in the middle. Finally quick turns in yaw. The parts where external vision data is not logged is where VIO is not able to track the motion and stops sending in data to EKF2. It resets itself and starts sending in external vision data when it tracks it again.

**Comment by devbharat** [comment]
Local position Z - External vision vs EKF2 estimate

Note: External vision sensor is below the IMU by 23 cm. So constant offset of 23cm is OK. Also, external vision data is 200ms delayed. Both the right parameters are set.

**LPOS.Z initialization**
lpos z initialization

**LPOS.Z tracking and divergence**
lpos z tracking and divergence
[lpos z tracking and divergence2](https://cloud.githubusercontent.com/assets/3105122/14832078/ab942482-0bf8-11e6-8cdb-bd037519e7c5.png)

You can see that the Blue line (external vision Z stops sometimes and starts again at different value when it resets).
The external vision height is fused with 1cm variance.

**Comment by priseborough** [comment]
Based on the innovation variances breaching their threshold whenever there is significant movement, you have a filter tuning problem. The current filter tuning filter will not work with position and height observation variances that small. If you want me to assist you with a tuning, then you need to provide add EV data to the replay facility. This is strongly advisable anyway as without the ability to replicate behaviour off-line it becomes extremely difficult to debug bad behaviour and develop fixes.

**Comment by priseborough** [comment]
@devbharat: I have rebased this on PR  #117 which is about to be pulled in.

You can find the rebase here: https://github.com/PX4/ecl/tree/pr-visionSupportRebase

We are still lacking the logging and replay changes on the PX4 side required for me to test this PR

**Comment by priseborough** [comment]
Rebased

**Comment by LorenzMeier** [comment]
@priseborough I presume you haven't seen this PR?
https://github.com/PX4/Firmware/pull/4382

**Comment by priseborough** [comment]
The EKF is fusing the EV position data correctly, but not the yaw data so I need to do some further debugging work.

**Comment by priseborough** [comment]
Bug preventing use of vision yaw data has been fixed.

**Comment by devbharat** [comment]
Thanks

**Comment by priseborough** [comment]
Testing on replay logs using GPS, range finder, Baro and optical flow data passes. I'm happy to merge this as soon as the pending items on PX4/Firmware#4382 are completed (rebase and addition of the interface code for  position and yaw 1-sigma observation error) .

**Comment by priseborough** [comment]
This is starting to block other work, so I will pull it in as the remaining work is outside the ecl library and it passes testing. Flight test on a pixracer board with default parameters here:

http://logs.uaventure.com/view/wfws8hYiuZJMF8rMxnaCRT

**Pull request merged**
