### PR TITLE
Edit true airspeed setpoint 

### PR DESCRIPTION
**Pull request by moreba1**
https://github.com/PX4/Firmware/issues/13090

### CODE REVIEW

**Comment by CarlOlsson** [comment]
Hi!
Why do you want to remove the conversion from equivalent airspeed to true airspeed in TECS?

**Comment by moreba1** [comment]
Airspeed setpoint by user is true airspeed and don't need to coversion.

**Comment by CarlOlsson** [comment]
Please explain more in depth your proposed change.
Why do you think the user should command TAS instead of EAS? With this change the aircraft will stall at minimum airspeed at high altitudes.

**Comment by priseborough** [comment]
This is an unsafe change as indicatged by @CarlOlsson

**Pull request closed without merging**
