### PR TITLE
Add DataValidatorGroup tests, add more DataValidator tests

### PR DESCRIPTION
**Pull request by tstellanova**
- Added more tests for DataValidator
- Initial set of tests for DataValidatorGroup

This should cover most of the validation code in CI. 
However there are a few cases (marked with TODO) that need more complete coverage.

### CODE REVIEW

**Comment by tstellanova** [comment]
Looks like CI build timed out..strange

**Comment by dagar** [comment]
The dynamic slaves have been failing to start. Let me restart to try again...

**Comment by dagar** [comment]
CI failures are now real.

**Comment by tstellanova** [comment]
Tests fixed and passing in CI

**Comment by tstellanova** [comment]
Looks like dynamic CI provisioning is stalled again...

**Pull request merged**
