### PR TITLE
EKF: Enable use of flow sensors that do not have gyros

### PR DESCRIPTION
**Pull request by priseborough**
Replaces https://github.com/PX4/ecl/pull/453

If optical flow gyro delta angles are set to NAN, then the EKF's internal IMU sample will be used.

TODO testing

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Firmware PR is merged, so you should be able to consolidate this all.

**Comment by mhkabir** [comment]
I did not look deeply into the diff, but does this take into account the delay of the optical flow measurement? For different sensors this could be much higher, upto 40-50ms.

**Comment by priseborough** [comment]
That is handled intrinsically because the accumulated gyro and optical flow measurements are brought together at the fusion time horizon

**Comment by priseborough** [comment]
I've done another review pass on the exisiting sensor buffering code and I think we still have a half optical flow frame time offset mismatch between the flow data and the gyro data because the time stamp for the flow data is set to the middle of the integration time period, not the end. 

This means the gyro data that is used to do the accumulation for the _imu_del_ang_of class variable will need to retrieved from the buffer separately using a time stamp that is the same as the end of the optical flow integration period instead of the midpoint. This won't take long to do.

**Comment by priseborough** [comment]
I've pushed a commit which should fix the difference in definition of the sampling time used in the optical flow buffer vs the sampling time required to accumulated gyro data. 

It also fixes  a pre-exisiting bug that meant the gyro data used to calculate the flow sensor gyro bias corrections was only accumulating EKF gyro data when new flow data arrived.

 I will go through it again tomorrow to see if I can spot anything else that has been missed.

**Comment by RomanBapst** [comment]
@priseborough Can you please have a look at the commit I added? I think the sign of the gyro data when it was taken from the ekf was not correct. I tested in SITL and also on the crazyfly.
On the crazyfly I additionally had the issue that the flow data seemed to have signs inverted. However, I think this may be a problem in the optical flow driver used for the crazyfly which I need to have a look at with @DanielePettenuzzo 
@DanielePettenuzzo  We also need to add the newly introduced flow constraints to the driver, otherwise the ekf will not accept the flow data. I will do a pull request for that tomorrow.

**Comment by priseborough** [comment]
@RomanBapst Thanks for spotting that.

On the subject of flow constraints, are you talking about the maximum flow rate? If so we need to find the value at which the sensor stops being accurate and set the associated EKF2 parameter appropriately in the crazyflie config file, rather than applying a flow limit in the sensor.

**Comment by RomanBapst** [comment]
@priseborough Ok, I'll have a look and update those parameters.

**Comment by mhkabir** [comment]
These are the parameters your crazyflie driver needs to read in and publish to uORB : https://github.com/PX4/Firmware/blob/master/src/modules/sensors/sensor_params_flow.c

**Comment by priseborough** [comment]
@RomanBapst and @mhkabir , can one of you please repeat your review. The last one you did has been dismissed by recent changes.

**Comment by RomanBapst** [comment]
@priseborough Here is a log from a flight with optical flow. Since we did not get the crazyzfly to work we decided to put the bitcraze optical flow deck on the S500 frame (similar to F450). The tests went very well, very stable flight and low drift. Unfortunately, we were constrained to fly at low altitude due to the teraranger's inability to measure in excess of 1.5 m.
https://logs.px4.io/plot_app?log=3fd36665-7441-4d21-b2a8-dc1e499f17f2

**Comment by priseborough** [comment]
Thanks Roman, the logs looks good. I like the idea of using that sensor on a a different airframe for testing - do you have a description of how that was wired up?

**Comment by RomanBapst** [comment]
@priseborough We were using a prototype version of the board that has a different pinout.
I found this on the web for the breakout board
expansion_board_pinout

The flow sensor is connected via SPI so the relevant pins would be
VCC, SCK, MISO, MOSI and GND

Here are the schematics
https://wiki.bitcraze.io/_media/projects:crazyflie2:expansionboards:flow-deck_reve.pdf

We will start documenting this properly as we plan to use those widely.

**Comment by RomanBapst** [comment]
@priseborough I forgot one pin, you need to also connect I03 pin which is the chip select pin (SS).

**Pull request merged**
