### PR TITLE
EKF: Add additional velocity interface to use landing beacon data

### PR DESCRIPTION
**Pull request by priseborough**
See https://github.com/PX4/Firmware/pull/8160 for details

### CODE REVIEW

**Comment by TSC21** [comment]
@priseborough I ask you if it is possible to extend this velocity interface to include the vertical velocity Z component? The reason is that for the case of the beacon, we are using the X/Y velocities, but when we have full pose estimation of a landing target being visually tracked (which I'll be adding the extension after PX4/Firmware#8160 is merged), we also have the Z component of it.

**Comment by priseborough** [comment]
It is possible, but should be done in conjunction with extending the landing_target_pose message. This  should include the z states, corresponding variances and separate validity for the vertical states.

When this is in place I will create another PR for ecl/EKF.

**Comment by TSC21** [comment]
> It is possible, but should be done in conjunction with extending the landing_target_pose message. This should include the z states, corresponding variances and separate validity for the vertical states.
>
>When this is in place I will create another PR for ecl/EKF.

Sounds good to me. Will add it then when I do I do the upgrade.

**Comment by priseborough** [comment]
SITL test log here: https://logs.px4.io/plot_app?log=97145626-db8c-4743-90f8-c4632a3bcde8

The following plot shows the velocity innovations from the GPS and landing target.

screen shot 2017-11-21 at 11 54 26 am

**Pull request merged**
