### PR TITLE
Conversion error correction and additional function overloads to allow standalone compilation.

### PR DESCRIPTION
**Pull request by mcsauder**
Hi There!

We found a copy/paste error in deg to rad conversion that gave some fun (quizzical) results! :)

Also, there were a few function overloads required in mathlib in order to allow standalone compile when Eigen is not included.  (P.S. we love Eigen, just keeping things minimal in this case.)

Please let me know if you have any questions on this PR.  Thanks for all of the work you've been up to in the ECL!

-Mark

### CODE REVIEW

**Comment by mcsauder** [comment]
Hi again,
My Travis CI build failed, but its not my fault!!! I promise. :) The fail isn't coming from one of the files I changed in this pull request.... if it's useful I can make a commit to make the required change as well.

Let me know what's best and I'm happy to do whatever I can!

-Mark

**Comment by dagar** [comment]
Is there a reason the build downloads, compiles, and install eigen every time? Would the Ubuntu packaged version 3.2.0 be acceptable?

**Comment by mcsauder** [comment]
Hi Dan,

I'm not sure. Is it the Travis CL you are referring to?  As for as this PR, when I work in Ubuntu, life is great, but for this project we need to be able to compile in Atmel Studio which is based on Visual Studio, is Windows (only), and makes life harder when including Eigen to build.  Because the ECL is so close to not requiring Eigen at all, and because this removes the ECL's dependency on either Limits.cpp/hpp or Eigen, it seemed like good sense to submit this as a PR.  If you might have a better suggestion, or if I didn't understand your question well, please let me know! 

-Mark

**Comment by dagar** [comment]
I just saw your comment about travis-ci failing in my github feed, and wondered if you knew anything about the eigen version requirements after I saw it being manually downloaded.

Is there value in having one build with eigen and one without?

**Comment by mcsauder** [comment]
Hi Dan,

Sorry about that comment, I deleted it... (embarrassingly), it was the last commit that I made which was the problem with Travis CI... I have no explanation why that allows us to build in Atmel Studio but Travis CI doesn't like it... I apologize for my misunderstanding of that.

-Mark

**Comment by dagar** [comment]
No worries. I was just browsing github on a quiet Friday night.

**Pull request merged**
