### PR TITLE
[WIP] Add check that the range finder data quality.

### PR DESCRIPTION
**Pull request by jiejiezhang**
In many cases, the ultrasonic data is abnormal, resulting in an abnormal height, so we should add ultrasonic data quality detection. It will be safer.
 @priseborough  Could you see the PR? Thanks!

### CODE REVIEW

**Comment by xdwgood** [comment]
It is important to ensure the credibility of this quality :smiley:

**Comment by priseborough** [comment]
Where is it supposed to get the range finder quality from?

**Comment by priseborough** [comment]
I think we should make following changes to achieve the objective:

1) Modify the setRangeData function so that it rejects range data if distance_sensor.covariance is <=0
2) Modify the EKF to use the maximum of the distance_sensor.covariance or sensor noise parameter
3) Ensure that all range sensor drivers publish an accuracy.
4) Fix the naming convention for distance_sensor.covariance because it is incorrect. Firstly a single measurement can't have a covariance and if it is supposed to be a variance, then it should have units of m^2. My preference is that that message represents the 1-sigma error and be named distance_sensor.accuracy.

**Comment by jiejiezhang** [comment]
> I think we should make following changes to achieve the objective:

Will do now as you suggestion. Thanks!!!!!!!!!!!! :+1:

**Pull request closed without merging**
