### PR TITLE
fixed computation of range measurement timestamp

### PR DESCRIPTION
**Pull request by tumbili**
Signed-off-by: Roman <bapstroman@gmail.com>

### CODE REVIEW

**Comment by priseborough** [comment]
The additional delay (1/2 sampling interval) added assumes that range data is down-sampled using an a averaging technique. Is this confirmed as correct?

**Comment by tumbili** [comment]
@priseborough Sorry for the delay. The assumption of an averaging technique does not apply to the range finder. Additionally, I don't think it applies for the mag and baro data.

**Comment by priseborough** [comment]
So as far as you know we are using the most recent sensor sample with no downsampling technique that would introduce a delay?

**Comment by tumbili** [comment]
@priseborough Yes, as far as I know. We need to see if this also applies to the baro and the mag samples because we have the delay in there now. @julianoes Is there any down-sampling happening for baro / mag sensor data?

**Comment by julianoes** [comment]
@tumbili I don't think so but I'd have to check in source.

**Comment by tumbili** [comment]
@priseborough Updated this according to the discussion. I've also opened another issue for the other two sensor #192

**Pull request merged**
